Practica4/Practica4/Controllers/PerfilController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Practica4.Controllers
{
    public class PerfilController : Controller
    {
        // GET: Perfil
        public ActionResult vPerfil()
        {
            return View();
        }

        public ActionResult IrA(string v)
        {
            return RedirectToAction(v, "Perfil");
        }

    }
}

Practica4/Practica4/Controllers/TipoCambioController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Practica4.Controllers
{
    public class TipoCambioController : Controller
    {
        // GET: TipoCambio
        public ActionResult Index(String date)
        {
            WSBanguat.TipoCambioSoapClient ws = new WSBanguat.TipoCambioSoapClient();
            ViewBag.tipoCambio = ws.TipoCambioDia().CambioDolar[0].fecha ;
            ViewBag.referencia = ws.TipoCambioDia().CambioDolar[0].referencia;


            string fecha = (date == null) ? DateTime.Now.ToShortDateString().ToString() : (Convert.ToDateTime(date).ToShortDateString().ToString()) ;
            ViewBag.tabla = ws.TipoCambioFechaInicial(fecha).Vars;
            
            return View();
        }
    }
}

Practica4/Practica4/Controllers/TransMonetariaController.cs
using Practica4.Models;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.SqlClient;
using System.Diagnostics;
using System.Linq;
using System.Web;
using System.Web.Mvc;

 namespace Practica4.Controllers
{
    public class TransMonetariaController : Controller
    {
        
        // GET: TransMonetaria
        public ActionResult vTransMonetaria()
        {
            return View();
        }

        
        //POST: Formualario
        [HttpPost]
        public ActionResult vTransMonetaria(string nombre, string apellido, long edad)
        {
            
            ViewBag.MeLlamo = nombre;
            ViewBag.Aficion = apellido;
            ViewBag.MiEdad = edad;
            List<ObjectUsuario> milista= getCuenta(nombre,apellido,edad);
            if (milista.Count == 0)
            {
                Response.Write("<script>alert('Error: El usuario: " + nombre + " " + apellido + " no tiene cuenta,verifique los datos');</script>");
                return View();
            }
           
                TempData["nombre"] = nombre;
                TempData["apellido"] = apellido;
                TempData["cuenta"] = edad;

            return RedirectToAction("vTransferencia", "Transferencia");
        }

        [HttpGet]
        public List<ObjectUsuario> getCuenta(string nombre, string apellido,long cuenta)
        {
            List<ObjectUsuario> lista = new List<ObjectUsuario>();
            string consulta = "select * from usuario where no_cuenta= "+cuenta+" and nombres= "+ "\'" + nombre+ "\'" + " and apellidos= "+ "\'" + apellido+ "\'";
            DataTable dt = consultarBD(consulta);
            if (dt != null)
            {
                if (dt.Rows.Count > 0)
                {
                    foreach (DataRow row in dt.Rows)
                    {
                        ObjectUsuario nuevo = new ObjectUsuario();
                        nuevo.usuario = row["usuario"].ToString();
                        nuevo.nombres = row["nombres"].ToString();
                        nuevo.apellidos = row["apellidos"].ToString();
                        nuevo.dpi = row["dpi"].ToString();
                        nuevo.no_cuenta = row["no_cuenta"].ToString();
                        nuevo.saldo = row["saldo"].ToString();
                        nuevo.email = row["email"].ToString();
                        nuevo.password = row["password"].ToString();

                        lista.Add(nuevo);
                    }
                }
            }
            return lista;
        }
      

        public static DataTable consultarBD(string Consulta)
        {
            string credenciales = "server=.; database=Practica3y4 ; integrated security = true";
            SqlConnection conexion = new SqlConnection(credenciales);
            SqlDataAdapter adaptador = new SqlDataAdapter();
            DataTable ds = new DataTable();
            try
            {
                conexion.Open();
                SqlCommand sql = new SqlCommand();
                sql.CommandText = Consulta;
                sql.CommandType = CommandType.Text;
                sql.Connection = conexion;

                adaptador.SelectCommand = sql;
                adaptador.Fill(ds);
                conexion.Close();
                return ds;
            }
            catch (Exception ex)
            {
                Trace.WriteLine(Consulta);
                return null;
            }
        }

       
    }
}

Practica4/Practica4/Views/Perfil/vPerfil.cshtml
@{
    ViewBag.Title = "Perfil de Usuario";
    if (Session["CUENTA"] == null || Session["NOMBRE"] == null)
    {
        Response.Redirect("~/Login/vLogin");
    }
}


<div>
    <div class="jumbotron text-center" style="margin-bottom:0">
        <h1>Perfil de Usuario</h1>
    </div>

    <div id="form-div" style="text-align:center">
        <h2>Bienvenido(a) @Session["NOMBRE"]...!!!</h2>
        <h3>No. Cuenta: @Session["CUENTA"]</h3>
        @*<h3>Saldo Actual: @Session["SALDO"]</h3>*@
        <div class="row">
            <br />
            <div class="col-md-4 col-md-offset-4">
                <div class="login-panel panel panel-default">
                    <div class="panel-body">
                        <fieldset>
                            <br />
                            <a href="@Url.Action("ConsultarView", "ConsultarSaldo")" class="btn btn-lg btn-primary btn-block" id="consultar">Consultar Saldo</a>
                            <br /><br />
                            <a href="@Url.Action("vTransMonetaria", "TransMonetaria")" class="btn btn-lg btn-primary btn-block" id="transferencia">Transferencia Monetaria</a>
                            <br /><br />
                            <a href="@Url.Action("Index", "TipoCambio")" class="btn btn-lg btn-primary btn-block" id="tipoCambio">Tipo de Cambio</a>
                        </fieldset>
                    </div>
                </div>
            </div>
        </div>
    </div>

</div>